### ISSUE TITLE
Uncaught SyntaxError: Cannot use import statement outside a module (at index.js:1:1)

### ISSUE THREAD

**Issue by shanehoban** [Jonghakseo/chrome-extension-boilerplate-react-vite#135] opened 2023-06-17 15:35 UTC
I'm getting this issue when trying to use import in background.js:

```
import reloadOnUpdate from 'virtual:reload-on-update-in-background-script'
import browser from 'webextension-polyfill'
import supabase from '@src/utils/supabaseClient'

reloadOnUpdate('pages/background')

/**
 * Extension reloading is necessary because the browser automatically caches the css.
 * If you do not use the css of the content script, please delete it.
 */
reloadOnUpdate('pages/content/style.scss')

console.log('background loaded')
```

My supabase client is simply:

```
import { createClient } from '@supabase/supabase-js'

const supabase = createClient(
  'https://<my-project-id>.supabase.co',
  '<my-anon-key>',
)

export default supabase
```

My manifest:

```
import packageJson from './package.json'

/**
 * After changing, please reload the extension at `chrome://extensions`
 */
const manifest: chrome.runtime.ManifestV3 = {
  manifest_version: 3,
  name: packageJson.name,
  version: packageJson.version,
  description: packageJson.description,
  // options_page: "src/pages/options/index.html",
  background: {
    service_worker: 'src/pages/background/index.js',
    type: 'module',
  },
  action: {
    default_popup: 'src/pages/popup/index.html',
    default_icon: 'icon-34.png',
  },
  // chrome_url_overrides: {
  //   newtab: "src/pages/newtab/index.html",
  // },
  icons: {
    '128': 'icon-128.png',
  },
  content_scripts: [
    {
      matches: ['http://*/*', 'https://*/*', '<all_urls>'],
      js: ['src/pages/content/index.js'],
      // KEY for cache invalidation
      css: ['assets/css/contentStyle<KEY>.chunk.css'],
    },
  ],
  // devtools_page: "src/pages/devtools/index.html",
  web_accessible_resources: [
    {
      resources: ['assets/js/*.js', 'assets/css/*.css', 'icon-128.png', 'icon-34.png'],
      matches: ['*://*/*'],
    },
  ],
}

export default manifest

```

Any help greatly appreciated!

**Comment by Jonghakseo** [comment] 2023-06-23 06:35
That's weird, I tried the same reproduction of this issue in the next branch and it worked on my local environment.

Can you give us more information about where the reproduction differs from the actual behavior?

https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/tree/issue/135

**Comment by sumilraweng** [comment] 2023-07-20 08:54
> That's weird, I tried the same reproduction of this issue in the next branch and it worked on my local environment.
> 
> Can you give us more information about where the reproduction differs from the actual behavior?
> 
> https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/tree/issue/135
## In src/pages/background/index.ts you need to do  console.log("supabase-->", supabase); will get error
```
import reloadOnUpdate from "virtual:reload-on-update-in-background-script";
import browser from "webextension-polyfill";
import supabase from "@src/utils/superbaseClient";

reloadOnUpdate("pages/background");

/**
 * Extension reloading is necessary because the browser automatically caches the css.
 * If you do not use the css of the content script, please delete it.
 */
reloadOnUpdate("pages/content/style.scss");
console.log("supabase-->", supabase);
```

**Comment by Jonghakseo** [comment] 2023-07-20 09:15
Okay, so it seems to be outputting fine on my local environment, so I've added a console.log and pushed it to that clone branch.

Can we get some more information on the exact error message and the environment it's working in?

```ts
import reloadOnUpdate from "virtual:reload-on-update-in-background-script";
import browser from "webextension-polyfill";
import supabase from "@src/utils/superbaseClient";

reloadOnUpdate("pages/background");

/**
 * Extension reloading is necessary because the browser automatically caches the css.
 * If you do not use the css of the content script, please delete it.
 */
reloadOnUpdate("pages/content/style.scss");

console.log("background loaded");
console.log("supabase", supabase);

```

### DEV(`yarn dev`)
<img width="944" alt="스크린샷 2023-07-20 오후 6 12 09" src="https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/assets/53500778/31d69a72-fb60-4d4d-8f36-98c51af47768">

### PROD(`yarn build`)

<img width="955" alt="스크린샷 2023-07-20 오후 6 14 11" src="https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/assets/53500778/68be1226-5c0e-402b-9cd7-1b08e9e16e37">

**Comment by sumilraweng** [comment] 2023-07-20 09:26
> Okay, so it seems to be outputting fine on my local environment, so I've added a console.log and pushed it to that clone branch.
> 
> Can we get some more information on the exact error message and the environment it's working in?
> 
> ```ts
> import reloadOnUpdate from "virtual:reload-on-update-in-background-script";
> import browser from "webextension-polyfill";
> import supabase from "@src/utils/superbaseClient";
> 
> reloadOnUpdate("pages/background");
> 
> /**
>  * Extension reloading is necessary because the browser automatically caches the css.
>  * If you do not use the css of the content script, please delete it.
>  */
> reloadOnUpdate("pages/content/style.scss");
> 
> console.log("background loaded");
> console.log("supabase", supabase);
> ```
> 
> ### DEV(`yarn dev`)
> <img alt="스크린샷 2023-07-20 오후 6 12 09" width="944" src="https://user-images.githubusercontent.com/53500778/254835596-31d69a72-fb60-4d4d-8f36-98c51af47768.png">
> ### PROD(`yarn build`)
> <img alt="스크린샷 2023-07-20 오후 6 14 11" width="955" src="https://user-images.githubusercontent.com/53500778/254836230-68be1226-5c0e-402b-9cd7-1b08e9e16e37.png">

### yes you are right, console.log is working in service worker log but in Chrome console you will look you get an error
<img width="1361" alt="image" src="https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/assets/73871290/4c1ec730-eee1-45c9-9680-207ed8ebbff1">

**Comment by Jonghakseo** [comment] 2023-07-20 11:10
@sumilraweng 

Ok. Can you try pulling the issue 135 branch again and see if the issue is reproduced? I've done this because I think it's a problem with the dynamic loading of the module.

**Comment by Jonghakseo** [comment] 2023-07-20 11:12
Note that it's not fully resolved, and we'll merge it into the main branch as a formal PR once we're sure of the issue.

**Comment by tushar1998** [comment] 2023-07-20 17:17
@sumilraweng try this solved using dynamic imports - https://github.com/tushar1998/chrome-extension-rollup

**Comment by PatrykKuniczak** [comment] 2023-09-18 20:35
@Jonghakseo that issue is solved or no?

**Comment by Jonghakseo** [comment] 2023-09-26 09:38
- https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/pull/188

For now, I've been using require inside my background script to import modules to bypass the issue with dynamic imports. This seems to have addressed the case in the current issue.

```ts
const browser = require("webextension-polyfill");
const supabase = require("@src/utils/superbaseClient");
```

**Comment by PatrykKuniczak** [comment] 2023-11-05 07:28
@Jonghakseo Maybe the same workaround works for background: 
https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/issues/160#issuecomment-1793660813

**Comment by PatrykKuniczak** [comment] 2023-11-05 13:47
@Jonghakseo We can do it also for background, like in: #246  ?

**Comment by Jonghakseo** [comment] 2023-11-05 13:55
In the background script, the import works fine. The problem was that when I used import in the background script, I got an error in the content script.

With the fix, I think we can close this issue now. If anyone else encounters the same issue, please reopen the issue.

**Closed by Jonghakseo** 2023-11-05 13:55 UTC
