### ISSUE TITLE
"Failed to load extension" error when Load Unpacked

### ISSUE THREAD

**Issue by tonychandesign** [Jonghakseo/chrome-extension-boilerplate-react-vite#64] opened 2023-03-20 00:51 UTC
Hello!

Thanks for taking the time to create this boilerplate.

I'm trying to set it up but running into an odd error when clicking the Load unpacked button within chrome://extensions/

I select the dist folder then I get an modal popup error saying:

Failed to load extension
File
~/Desktop/chan-extension/dist
Error
Could not load css 'assets/css/contentStyle1679273105255.chunk.css' for content script.
Could not load manifest.

I've attached a screenshot... I can't find much info on this error online but it seems to be related incorrect naming within the manifest file?

<img width="1133" alt="Screenshot 2023-03-20 at 00 50 12" src="https://user-images.githubusercontent.com/22465526/226222113-cffbbee4-84ea-43a7-bbe0-863d33fa993e.png">

**Comment by Jonghakseo** [comment] 2023-03-20 01:06
Have you checked if the issue persists in the latest version?

**Comment by Jonghakseo** [comment] 2023-03-20 16:02
@tonychandesign 

Well, seems like we've got a funny little situation here. We've noticed that Date.now occasionally returns with a 1ms discrepancy when generateKey is called repeatedly. Thank you for bringing this to our attention - it's not the prettiest fix, but we've taken care of it promptly.

- https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/pull/70

**Comment by dvalbuena1** [comment] 2023-03-25 02:48
I believe the error may still be present.
A funny thing that is happening to me is that every time I do npm dev the manifest.json file stores the key generated by the previous execution of the command.

Eg.
![image](https://user-images.githubusercontent.com/44622851/227682841-0da89399-2cc7-4c54-b577-7c60b42aa9ba.png)

After running again the command you can see that the old css file has been deleted but the manifest.json has the same key.

![image](https://user-images.githubusercontent.com/44622851/227683084-5d354a10-5b77-4ea3-a2bf-ca5178cec8d5.png)

**Comment by Jonghakseo** [comment] 2023-03-25 03:52
@dvalbuena1 

Hello! I'm sorry to give you this answer, but it's difficult for me to identify the issue in my environment. Can you provide more information?

**Comment by dvalbuena1** [comment] 2023-03-26 23:01
Well, there is not much additional information to highlight. At the moment I am using the latest commit of the main.  

The only change I have made so far has been the following in order to be able to run it correctly from Windows.
![image](https://user-images.githubusercontent.com/44622851/227810138-8df42c87-3404-46f8-b830-6c239d46df3e.png)

And the version of Node I am using is 16.19.1

**Comment by dvalbuena1** [comment] 2023-03-28 17:43
I think the problem happens because when you run the program in dev mode it first copies the manifest.json file from the public folder to the dist folder and then it generates the new manifest.json in the public folder.
For this reason the manifest.json seems to remain with the previous version.

**Comment by TP-O** [comment] 2023-03-31 15:53
@Jonghakseo The problem here is that `__DEV__` isn't loaded yet. I recommend to use [cross-env](https://www.npmjs.com/package/cross-env) to load environment variables because  it works on both windows and linux.

**Comment by Jonghakseo** [comment] 2023-04-02 03:48
The pull request suggested by @TP-O has been merged. Please check back to see if the issue is reproduced, and if so, we'll close the issue.

**Comment by benschac** [comment] 2023-04-08 14:57
still having the same issue here, with cross-env

**Comment by noga-dev** [comment] 2023-04-08 15:04
> still having the same issue here, with cross-env

Worked for me.

**Comment by Jonghakseo** [comment] 2023-06-13 02:17
This issue has been closed for a long time with no additional information provided. If anyone encounters the same issue, you can re-open it with your running environment and error logs attached.

**Closed by Jonghakseo** 2023-06-13 02:17 UTC
Labels: help wanted

**Comment by Jonghakseo** [comment] 2023-10-15 07:59
@all-contributors please add @TP-O for bug

**Comment by Jonghakseo** [comment] 2023-10-15 07:59
@all-contributors please add @tonychandesign for bug

**Comment by jgoedde** [comment] 2023-10-27 09:37
Hey. I am encountering the same issue. Just cloned the repo today. First time it ran perfectly but now even after re-cloning still having the same issue.

**Comment by Jonghakseo** [comment] 2023-11-09 23:55
@jgoedde 

That's weird, your screenshot is very different from the typical post-build output.

<img width="380" alt="스크린샷 2023-11-10 오전 8 55 18" src="https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite/assets/53500778/c9523761-147e-41b6-9b1e-70187c7ee2ae">

It could be an operating system issue.
I suspect the behavior of the path module, could you try debugging the assetFileNames part of vite.config.ts?
