### ISSUE TITLE
New extension ID created on new build 

### ISSUE THREAD

**Issue by remusris** [Jonghakseo/chrome-extension-boilerplate-react-vite#53] opened 2023-01-22 00:38 UTC
There's a new extension ID that gets created on new builds that prevents from me validating oauth

**Comment by Jonghakseo** [comment] 2023-03-11 17:14
Can you elaborate on what the issue is?

**Comment by Jonghakseo** [comment] 2023-05-28 09:05
We will close this issue as there has been no additional feedback for a long time.

**Closed by Jonghakseo** 2023-05-28 09:05 UTC
Labels: help wanted
